#!/bin/bash
# ============================================================================
# Hermes Orchestrator Installer (Colmeio Edition)
# ============================================================================
#
# Usage:
#   curl -fsSL https://raw.githubusercontent.com/Magaav/hermes-orchestrator/main/scripts/install.sh | bash
#
# ============================================================================
set -e

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
CYAN='\033[0;36m'
NC='\033[0m'
BOLD='\033[1m'

REPO_URL="https://github.com/Magaav/hermes-orchestrator.git"
INSTALL_DIR="${HERMES_ORCHESTRATOR_DIR:-/local}"
HORC_INSTALL_PATH="${HORC_INSTALL_PATH:-/usr/local/bin/horc}"

info()    { echo -e "${CYAN}[horc]${NC} $1"; }
success() { echo -e "${GREEN}[horc]${NC} $1"; }
warn()    { echo -e "${YELLOW}[horc]${NC} $1"; }
error()   { echo -e "${RED}[horc]${NC} $1"; }

# Parse arguments
BRANCH="main"
while [[ $# -gt 0 ]]; do
    case $1 in
        --branch) BRANCH="$2"; shift 2 ;;
        --dir) INSTALL_DIR="$2"; shift 2 ;;
        -h|--help)
            echo "Hermes Orchestrator Installer"
            echo ""
            echo "Usage: curl -fsSL ... | bash [OPTIONS]"
            echo ""
            echo "Options:"
            echo "  --branch NAME  Git branch (default: main)"
            echo "  --dir PATH    Install directory (default: /local)"
            echo "  -h, --help    Show this help"
            exit 0 ;;
        *) shift ;;
    esac
done

info "Hermes Orchestrator installation starting..."
info "Target: ${INSTALL_DIR}"

# Detect if already installed
if [[ -d "${INSTALL_DIR}/hermes-agent" ]] || [[ -d "${INSTALL_DIR}/scripts" ]]; then
    warn "Existing installation detected. Updating instead of fresh install."
    UPDATE_MODE=true
fi

# Clone or pull
if [[ -d "${INSTALL_DIR}/.git" ]] || [[ -d "${INSTALL_DIR}/hermes-agent" ]]; then
    info "Repository exists — pulling latest..."
    cd "${INSTALL_DIR}"
    git fetch origin "${BRANCH}"
    git checkout "${BRANCH}"
    git pull origin "${BRANCH}"
else
    info "Cloning repository..."
    git clone --branch "${BRANCH}" --depth 1 "${REPO_URL}" "${INSTALL_DIR}"
fi

# Install horc command
info "Installing 'horc' command..."
HORC_BIN_CONTENTS="#!/bin/bash
# horc — Hermes Orchestrator Clone Manager
# Auto-generated by install.sh

HERMES_CLONE_MANAGER_SCRIPT=\"${INSTALL_DIR}/scripts/clone/clone_manager.py\"
PYTHON_BIN=\"${INSTALL_DIR}/hermes-agent/.venv/bin/python3\"
if [[ ! -x \"\${PYTHON_BIN}\" ]]; then
    PYTHON_BIN=\"\$(command -v python3 || command -v python || true)\"
fi
if [[ -z \"\${PYTHON_BIN}\" ]]; then
    echo \"horc: python runtime not found\" >&2
    exit 1
fi
if [[ ! -f \"\${HERMES_CLONE_MANAGER_SCRIPT}\" ]]; then
    echo \"horc: clone_manager.py not found at \${HERMES_CLONE_MANAGER_SCRIPT}\" >&2
    exit 1
fi

# Map horc verbs to clone_manager verbs
ACTION=\"\${1:-}\"
case \"\${ACTION}\" in
    status|start|stop|delete|restart|reboot|logs|purge)
        exec \"\${PYTHON_BIN}\" \"\${HERMES_CLONE_MANAGER_SCRIPT}\" \"\$@\"
        ;;
    add)
        exec \"\${PYTHON_BIN}\" \"\${HERMES_CLONE_MANAGER_SCRIPT}\" add \"\$2\" \"\${@:3}\"
        ;;
    del|remove)
        exec \"\${PYTHON_BIN}\" \"\${HERMES_CLONE_MANAGER_SCRIPT}\" del \"\$2\" \"\${@:3}\"
        ;;
    list|ls)
        exec \"\${PYTHON_BIN}\" \"\${HERMES_CLONE_MANAGER_SCRIPT}\" list
        ;;
    -h|--help|help)
        echo \"horc — Hermes Orchestrator Clone Manager\" >&2
        echo \"\" >&2
        echo \"Usage: horc <command> [args]\" >&2
        echo \"\" >&2
        echo \"Commands:\" >&2
        echo \"  horc list                  List all clones\" >&2
        echo \"  horc status <name>          Show clone status\" >&2
        echo \"  horc start <name>           Start (or restart) clone\" >&2
        echo \"  horc stop <name>            Stop clone\" >&2
        echo \"  horc restart <name>         Restart gateway (inside container)\" >&2
        echo \"  horc reboot <name>          Reboot container\" >&2
        echo \"  horc delete <name>          Delete clone\" >&2
        echo \"  horc logs <name> [--lines]  View logs\" >&2
        echo \"  horc add <name> [args]      Add new clone\" >&2
        echo \"  horc del <name>             Delete clone\" >&2
        exit 0
        ;;
    *)
        if [[ -z \"\$ACTION\" ]]; then
            echo \"horc: no command specified. Run 'horc --help' for usage.\" >&2
        else
            echo \"horc: unknown command '\$ACTION'. Run 'horc --help' for usage.\" >&2
        fi
        exit 1
        ;;
esac
"

echo "$HORC_BIN_CONTENTS" > "${HORC_INSTALL_PATH}"
chmod +x "${HORC_INSTALL_PATH}"

success "'horc' installed to ${HORC_INSTALL_PATH}"

# Show horc help
echo ""
success "Installation complete!"
echo ""
echo -e "${BOLD}Usage:${NC}"
echo "  horc list                  List all clones"
echo "  horc status <name>         Show clone status"
echo "  horc start <name>          Start (or restart) clone"
echo "  horc stop <name>           Stop clone"
echo "  horc restart <name>        Restart gateway (inside container)"
echo "  horc reboot <name>         Reboot container"
echo "  horc delete <name>         Delete clone"
echo "  horc logs <name>           View logs"
echo "  horc add <name> [args]     Add new clone"
echo ""
echo -e "${BOLD}Examples:${NC}"
echo "  horc list"
echo "  horc status colmeio"
echo "  horc start colmeio"
echo "  horc logs colmeio --lines 50"
echo ""
