import assert from "node:assert/strict";
import fs from "node:fs/promises";

const root = new URL("../public/modules/browser/", import.meta.url);
const entry = await fs.readFile(new URL("browser.entry.js", root), "utf8");
const descriptor = await fs.readFile(new URL("module.js", root), "utf8");
const appRegistry = await fs.readFile(new URL("../public/modules/app-registry.js", import.meta.url), "utf8");
const appShell = await fs.readFile(new URL("../public/app.js", import.meta.url), "utf8");
const preload = await fs.readFile(new URL("../../../native/windows/src/preload.js", import.meta.url), "utf8");
const manager = await fs.readFile(new URL("../../../native/windows/src/main/web-surfaces/manager.js", import.meta.url), "utf8");
const manifest = JSON.parse(await fs.readFile(new URL("../../../native/windows/src/main/web-surfaces/capability-manifest.json", import.meta.url), "utf8"));
const builder = JSON.parse(await fs.readFile(new URL("../../../native/windows/src/electron-builder.json", import.meta.url), "utf8"));

assert.match(entry, /wasmAgentNative\?\.webSurfaces/);
assert.match(entry, /Native Chromium is available in the Electron build only/);
assert.match(entry, /invoke\("input-receipt", \{ enabled \}\)/);
assert.match(entry, /web_surface\.input_receipt/);
assert.match(entry, /const ready = next\.status === "ready"/);
assert.match(entry, /revision !== overlayRevision[\s\S]{0,120}scheduleGeometry\(\)/);
assert.match(descriptor, /browser\.entry\.js\?v=20260822-surface-readiness1/);
assert.match(appRegistry, /browser\.entry\.js\?v=20260822-surface-readiness1/);
assert.match(appShell, /app-registry\.js\?v=20260820-native-input-receipt2/);
assert.match(appRegistry, /export async function ensureExternalAppOpen/);
assert.match(appShell, /return ensureExternalAppOpen\(app, widgetLayout\(app\.id\)\.minimized/);
assert.match(appShell, /client-presence\.js\?v=20260820-active-space1/);
assert.doesNotMatch(entry, /iframe|transferControlToOffscreen|engine\.worker|extension-network/);
assert.match(descriptor, /browser\.native\.surface/);
assert.match(preload, /wasm-agent:web-surface/);
assert.match(manager, /canonicalChromeUserAgent\(chromeVersion\)/);
assert.match(manager, /webSession\.setUserAgent\(userAgent\)/);
assert.match(manager, /reloadIgnoringCache\(\)/);
assert.match(manager, /before-mouse-event/);
assert.match(manager, /includeInputReceipt/);
assert.match(manager, /sendInputEvent/);
assert.match(manager, /pointer-dispatch/);
assert.match(manager, /javascript-execute-unrestricted/);
assert.match(manager, /currentSurfaceStatus\(record/);
assert.match(manager, /native_web_surface_javascript_execution\.v1/);
assert.ok(manifest.capabilities.includes("web_surface.input_receipt"));
assert.ok(manifest.capabilities.includes("web_surface.pointer.dispatch"));
assert.ok(manifest.capabilities.includes("web_surface.javascript.execute.unrestricted"));
assert.equal(manifest.limits.inputReceiptMaxPerSurface, 1);
assert.equal(manifest.limits.inputReceiptTtlMs, 120000);
assert.ok(builder.files.includes("main/web-surfaces/manager.js"));
assert.ok(builder.files.includes("main/web-surfaces/capability-manifest.json"));
assert.ok(builder.files.includes("main/full-power-executor.js"));

console.log("native browser widget wiring tests passed");
