const assert = require("assert");
const fs = require("fs");
const path = require("path");

const pluginRoot = path.resolve(__dirname, "..");
const appJs = fs.readFileSync(path.join(pluginRoot, "public", "app.js"), "utf8");
const indexHtml = fs.readFileSync(path.join(pluginRoot, "public", "index.html"), "utf8");
const stylesCss = fs.readFileSync(path.join(pluginRoot, "public", "styles.css"), "utf8");
const swJs = fs.readFileSync(path.join(pluginRoot, "public", "sw.js"), "utf8");
const iconSvg = fs.readFileSync(path.join(pluginRoot, "public", "icons", "icon.svg"), "utf8");
const modulesIndexJs = fs.readFileSync(path.join(pluginRoot, "public", "modules", "index.js"), "utf8");
const devHmrJs = fs.readFileSync(path.join(pluginRoot, "public", "modules", "hmr", "dev-hmr.js"), "utf8");
const manifest = JSON.parse(
  fs.readFileSync(path.join(pluginRoot, "public", "manifest.webmanifest"), "utf8")
);
const serverPy = fs.readFileSync(path.join(pluginRoot, "server", "static_server.py"), "utf8");
const designMd = fs.readFileSync(path.join(pluginRoot, "DESIGN.md"), "utf8");
const artifactsMd = fs.readFileSync(path.join(pluginRoot, "ARTIFACTS.md"), "utf8");
const imageCardGoldenPy = fs.readFileSync(path.join(pluginRoot, "tests", "image_card_golden.test.py"), "utf8");
const doctorSh = fs.readFileSync(path.join(pluginRoot, "scripts", "doctor.sh"), "utf8");
const removedHeaderName = "top" + "bar";
const removedFrameLabel = "frame" + "Label";
const removedWidgetLayerAttr = "data-widget-" + "layer";
const removedLayerDockState = "update" + "Layer" + "Dock";
const moduleFolders = [
  "hmr",
  "browser",
  "observation",
  "timeline",
  "assistant",
  "image-card-core",
  "barcode-reader",
  "ocr",
  "cv-shapes",
  "semantic-vision",
];

const match = appJs.match(/CORE_WASM_BASE64\s*=\s*"([^"]+)"/);
assert(match, "CORE_WASM_BASE64 was not found");

(async () => {
  const bytes = Buffer.from(match[1], "base64");
  const { instance } = await WebAssembly.instantiate(bytes);
  assert.strictEqual(instance.exports.add(19, 23), 42);
  assert(appJs.trimStart().startsWith("import "), "module imports must stay before executable code");
  assert(appJs.includes('./modules/index.js'), "module registry import is missing");
  assert(appJs.includes('./modules/hmr/dev-hmr.js'), "dev HMR import must live under the hmr module folder");
  assert.strictEqual(manifest.name, "WASM Agent");
  assert.strictEqual(manifest.start_url, "/");
  assert.strictEqual(manifest.display, "standalone");
  assert(indexHtml.includes("os-shell"), "workspace shell markup is missing");
  assert(indexHtml.includes('data-panel="home"'), "initial home panel state is missing");
  assert(indexHtml.includes("__WASM_AGENT_DISABLE_SW__"), "dev service-worker reset guard is missing");
  assert(indexHtml.includes('data-panel="home"'), "home launcher target is missing");
  assert(indexHtml.includes('launcher-mark active'), "home launcher should be active on first paint");
  assert(indexHtml.includes("home-glyph"), "home launcher icon is missing");
  assert(indexHtml.includes("spaceLauncherList"), "dynamic space launcher list is missing");
  assert(appJs.includes('dataset.panel = "admin"'), "admin launcher target is missing");
  assert(!indexHtml.includes('data-view="admin"'), "admin summary panel should be removed");
  assert(appJs.includes('label.textContent = "Admin"'), "admin space label is missing");
  assert(appJs.includes("ADMIN_PANEL_IDS"), "admin panel registry is missing");
  assert(appJs.includes("createAdminCrownIcon"), "admin crown icon renderer is missing");
  assert(appJs.includes('value === "space" ? "admin"'), "legacy space route must land on admin");
  assert(stylesCss.includes(".admin-launch-button"), "admin launcher button styles are missing");
  assert(stylesCss.includes(".space-launch-crown"), "admin crown icon styles are missing");
  assert(indexHtml.includes("addSpaceButton"), "home add-space button is missing");
  assert(indexHtml.includes("homeConfigButton"), "home config button is missing");
  assert(indexHtml.includes("homeModulesButton"), "home modules button is missing");
  assert(indexHtml.includes("homeStorageBadge"), "home storage quota badge is missing");
  assert(indexHtml.includes("spaceConfigButton"), "per-space config button is missing");
  assert(indexHtml.includes("appLayer"), "space app layer is missing");
  assert(indexHtml.includes("spaceContextMenu"), "space context menu markup is missing");
  assert(indexHtml.includes("appContextMenu"), "app/widget context menu markup is missing");
  assert(indexHtml.includes("appEditModal"), "app/widget edit modal is missing");
  assert(indexHtml.includes("nodeEditModal"), "topology node edit modal is missing");
  assert(indexHtml.includes("deleteSpaceModal"), "delete-space modal is missing");
  assert(indexHtml.includes("launcherLogin"), "launcher login component is missing");
  assert(indexHtml.includes('data-auth="checking"'), "account auth gate state is missing");
  assert(indexHtml.includes("authGate"), "account auth gate markup is missing");
  assert(indexHtml.includes("authGateGoogleSignInButton"), "admin gate Google button slot is missing");
  assert(!indexHtml.includes("wasmStatus"), "bottom wasm status led should not be exposed in the launcher");
  assert(!indexHtml.includes("bridgeStatus"), "bottom bridge status led should not be exposed in the launcher");
  for (const panel of ["space", "fleet", "tasks", "logs", "observe", "modules"]) {
    assert(!indexHtml.includes(`class="launch" type="button" data-panel="${panel}"`), `${panel} must not be fixed in the global launcher`);
  }
  assert(indexHtml.includes('panel-view active" data-view="home"'), "homespace should be active on first paint");
  assert(iconSvg.includes("WASM Agent WA monogram icon"), "PWA icon should use the WA monogram asset");
  assert(!indexHtml.includes(removedHeaderName), "legacy header markup should be removed");
  assert(!stylesCss.includes(`.${removedHeaderName}`), "legacy header styles should be removed");
  assert(stylesCss.includes('.os-shell[data-panel="home"] .space-frame'), "home space-frame override is missing");
  assert(stylesCss.includes(".home-actions"), "home action group styles are missing");
  assert(stylesCss.includes(".home-action-button.primary"), "major New Space button style is missing");
  assert(stylesCss.includes("[hidden]"), "hidden modal/menu guard is missing");
  assert(stylesCss.includes(".space-context-menu"), "space context menu styles are missing");
  assert(stylesCss.includes(".modal-backdrop"), "modal backdrop styles are missing");
  assert(stylesCss.includes(".login-popover"), "launcher login popover styles are missing");
  assert(stylesCss.includes('.os-shell[data-auth="locked"] .main-stage'), "locked auth state must hide the app surface");
  assert(stylesCss.includes('.os-shell[data-auth="locked"] ~ .agent-overlay'), "locked auth state must hide assistant overlay");
  assert(stylesCss.includes(".auth-gate"), "account auth gate styles are missing");
  assert(stylesCss.includes(".space-launcher-list"), "space launcher list styles are missing");
  assert(stylesCss.includes("z-index: 25000"), "launcher and login popover must stay above the workspace canvas");
  assert(stylesCss.includes("width: 72px"), "launcher must own a stable 72px rail width");
  assert(stylesCss.includes('grid-template-rows: minmax(0, 1fr);'), "home main stage must collapse to the canvas row");
  assert(stylesCss.includes('grid-template-columns: 72px minmax(0, 1fr);'), "mobile launcher must keep the left-rail default");
  assert(stylesCss.includes('data-mobile-launcher="top"'), "mobile launcher top-bar preference styles are missing");
  assert(stylesCss.includes('grid-template-rows: 58px minmax(0, 1fr) auto;'), "launcher should keep the account component inside viewport");
  assert(!appJs.includes("USER_SPACES_STORAGE_KEY"), "user spaces must not persist in browser local storage");
  assert(appJs.includes("loadUserSpaces"), "server-backed user space loader is missing");
  assert(appJs.includes('action: "layout"'), "server-backed per-space layout persistence is missing");
  assert(serverPy.includes('state_dir / "users"'), "per-user state root is missing");
  assert(serverPy.includes('"spaces"'), "per-user space root is missing");
  assert(serverPy.includes("DEFAULT_USER_QUOTA_BYTES"), "per-user disk quota constant is missing");
  assert(appJs.includes("createUserSpace"), "home add-space handler is missing");
  assert(appJs.includes("showSpaceContextMenu"), "space right-click menu handler is missing");
  assert(appJs.includes("DELETE ${space.title}"), "delete-space confirmation phrase must include the space name");
  assert(appJs.includes("openConfigModal"), "home config modal controller is missing");
  assert(appJs.includes("openHomeModulesModal"), "home modules modal controller is missing");
  assert(appJs.includes("loadAuthSession"), "account session loader is missing");
  assert(appJs.includes("handleGoogleCredential"), "Google credential callback is missing");
  assert(appJs.includes("bootstrapAuthenticatedApp"), "app services must wait for authenticated account bootstrap");
  assert(appJs.includes("authGateLoginButton"), "auth gate login action is missing");
  assert(appJs.includes("authGateGoogleSignInButton"), "auth gate direct Google button renderer is missing");
  assert(appJs.includes("renderSpaceLauncher"), "dynamic launcher renderer is missing");
  assert(appJs.includes('"user-space"'), "dynamic spaces should use the user-space shell");
  assert(designMd.includes("WASM Agent Design Contract"), "wasm-agent design contract is missing");
  assert(designMd.includes("Icons must be centered"), "design contract must require centered button icons");
  assert(designMd.includes("Every frontend change"), "design contract must describe the frontend change gate");
  assert(indexHtml.includes('data-widget-id="topology"'), "draggable widget ids are missing");
  assert(indexHtml.includes('data-widget-id="browser-proof"'), "browser proof widget is missing");
  assert(indexHtml.includes("Host Browser"), "host browser widget label is missing");
  assert(indexHtml.includes("browserCanvas"), "browser stream canvas is missing");
  assert(indexHtml.includes("Hermes Topology"), "topology widget markup is missing");
  assert(indexHtml.includes('data-panel="observe"'), "observation inspector tab is missing");
  assert(indexHtml.includes("observationSnapshot"), "observation snapshot view is missing");
  assert(indexHtml.includes("observationTimeline"), "observation timeline view is missing");
  assert(indexHtml.includes('data-panel="modules"'), "module management panel target is missing");
  assert(indexHtml.includes("moduleList"), "module management list is missing");
  assert(indexHtml.includes('data-widget-id="timeline"'), "timeline widget is missing");
  assert(indexHtml.includes("timelineGraph"), "timeline graph is missing");
  assert(!indexHtml.includes("timelineCheckpointButton"), "manual timeline checkpoint control should not be exposed");
  assert(indexHtml.includes('data-module-target="host-browser"'), "host browser module target is missing");
  assert(indexHtml.includes('data-module-target="embedded-assistant"'), "embedded assistant module target is missing");
  assert(appJs.includes("MODULE_SETTINGS_STORAGE_KEY"), "module setting persistence is missing");
  assert(appJs.includes("MODULE_DEFINITIONS"), "module definitions are missing");
  assert(modulesIndexJs.includes("MODULE_DEFINITIONS"), "module registry export is missing");
  for (const folder of moduleFolders) {
    assert(fs.existsSync(path.join(pluginRoot, "public", "modules", folder, "module.js")), `${folder} module firmware descriptor is missing`);
    assert(modulesIndexJs.includes(`./${folder}/module.js`), `${folder} module is not linked from the registry`);
  }
  assert(!fs.existsSync(path.join(pluginRoot, "public", "modules", "dev-hmr.js")), "dev HMR firmware should be under modules/hmr");
  assert(appJs.includes("renderModules"), "module management renderer is missing");
  assert(appJs.includes("renderTimeline"), "timeline renderer is missing");
  assert(appJs.includes("/timeline/status"), "timeline status endpoint call is missing");
  assert(!appJs.includes("/timeline/checkpoint"), "manual timeline checkpoint client calls should be removed");
  assert(appJs.includes("setModuleEnabled"), "module toggle handler is missing");
  assert(appJs.includes("modules.setting_changed"), "module setting analytics are missing");
  assert(stylesCss.includes(".module-card"), "module card styles are missing");
  assert(stylesCss.includes(".module-toggle"), "module toggle styles are missing");
  assert(stylesCss.includes(".timeline-widget"), "timeline widget styles are missing");
  assert(stylesCss.includes(".timeline-node"), "timeline node styles are missing");
  assert(indexHtml.includes("agentOverlay"), "global embedded assistant overlay is missing");
  assert(indexHtml.includes("agentAvatarButton"), "global assistant avatar button is missing");
  assert(indexHtml.includes("agentForm"), "embedded assistant chat form is missing");
  assert(indexHtml.includes("agentDiagnostics"), "embedded assistant diagnostics panel is missing");
  assert(indexHtml.includes("agent-panel-title"), "embedded assistant chat title is missing");
  assert(indexHtml.includes(">Chat<"), "embedded assistant chat title text is missing");
  assert(indexHtml.includes("<dt>Mode</dt>"), "embedded assistant mode diagnostic is missing");
  assert(indexHtml.includes("<dt>Node</dt>"), "embedded assistant node diagnostic is missing");
  assert(indexHtml.includes("<dt>Turns</dt>"), "embedded assistant transcript diagnostic is missing");
  assert(indexHtml.includes("agentContextPreview"), "embedded assistant context preview is missing");
  assert(indexHtml.includes("agentModeSelect"), "embedded assistant mode selector is missing");
  assert(indexHtml.includes("agentNodeSelect"), "embedded assistant node selector is missing");
  assert(indexHtml.includes("agentSessionsButton"), "embedded assistant session icon button is missing");
  assert(indexHtml.includes("agentSessionsBalloon"), "embedded assistant session balloon is missing");
  assert(indexHtml.includes("agentSessionList"), "embedded assistant session list is missing");
  assert(indexHtml.includes("agentNewSessionButton"), "embedded assistant new session button is missing");
  assert(indexHtml.includes("New Chat"), "embedded assistant clean-session button title is missing");
  assert(indexHtml.includes("agentContextButton"), "embedded assistant context icon button is missing");
  assert(indexHtml.includes("agentContextBalloon"), "embedded assistant context balloon is missing");
  assert(indexHtml.includes("agentSettingsButton"), "embedded assistant settings icon button is missing");
  assert(indexHtml.includes("agentSettingsBalloon"), "embedded assistant settings balloon is missing");
  assert(indexHtml.includes("Auto</option>"), "embedded assistant Auto mode option is missing");
  assert(indexHtml.includes("uses the selected node for other messages"), "embedded assistant mode explanation is missing");
  assert(indexHtml.includes("agent-send-arrow"), "embedded assistant send arrow icon is missing");
  assert(indexHtml.includes("agent-send-stop"), "embedded assistant stop icon is missing");
  assert(indexHtml.includes("agentAttachButton"), "embedded assistant attach button is missing");
  assert(indexHtml.includes("m16.1 9.1"), "embedded assistant attach icon path should be valid");
  assert(stylesCss.includes(".agent-overlay"), "global assistant overlay styles are missing");
  assert(stylesCss.includes(".agent-diagnostics"), "embedded assistant diagnostics styles are missing");
  assert(stylesCss.includes(".agent-mode"), "embedded assistant mode selector styles are missing");
  assert(stylesCss.includes(".agent-balloon"), "embedded assistant balloon styles are missing");
  assert(stylesCss.includes(".agent-settings-balloon"), "embedded assistant settings balloon styles are missing");
  assert(stylesCss.includes(".agent-icon-settings"), "embedded assistant settings icon styles are missing");
  assert(stylesCss.includes(".agent-session-row"), "embedded assistant session row styles are missing");
  assert(stylesCss.includes(".agent-context-preview"), "embedded assistant context preview styles are missing");
  assert(stylesCss.includes(".agent-changed-details"), "embedded assistant changed-files details styles are missing");
  assert(stylesCss.includes("max-height: 124px"), "embedded assistant changed-files list must stay scroll limited");
  assert(stylesCss.includes(".agent-send-button.is-busy"), "embedded assistant send button busy state is missing");
  assert(stylesCss.includes(".agent-turn-header"), "embedded assistant thinking header styles are missing");
  assert(stylesCss.includes(".agent-message-menu"), "embedded assistant message action menu styles are missing");
  assert(stylesCss.includes(".agent-icon-copy"), "embedded assistant copy icon styles are missing");
  assert(stylesCss.includes(".agent-token-usage"), "embedded assistant token usage display styles are missing");
  assert(stylesCss.includes(".agent-actions-chain"), "embedded assistant action chain styles are missing");
  assert(stylesCss.includes(".agent-image-card"), "embedded assistant image-card styles are missing");
  assert(stylesCss.includes(".agent-image-card-metrics"), "embedded assistant image-card metric styles are missing");
  assert(stylesCss.includes(".agent-image-card-evidence"), "embedded assistant image-card evidence styles are missing");
  assert(stylesCss.includes(".agent-actions-summary"), "embedded assistant action summary styles are missing");
  assert(stylesCss.includes(".agent-action-kind"), "embedded assistant action kind badge styles are missing");
  assert(stylesCss.includes(".agent-action-preview"), "embedded assistant action preview styles are missing");
  assert(stylesCss.includes("justify-content: space-between"), "embedded assistant composer controls must sit below the text area");
  assert(stylesCss.includes(".agent-image-preview-remove"), "embedded assistant pending image remove control styles are missing");
  assert(stylesCss.includes("font-variant-numeric: tabular-nums"), "embedded assistant timer must use tabular numerals");
  assert(stylesCss.includes("border-radius: var(--radius)"), "embedded assistant send button must use standard rounded button shape");
  assert(stylesCss.includes("width: 34px"), "embedded assistant send button must be 34px wide");
  assert(!stylesCss.includes(".patch-proposal"), "patch proposal card styles should be removed");
  assert(stylesCss.includes("z-index: 30000"), "assistant overlay must top app layers");
  assert(appJs.includes("startDevHmr"), "dev HMR module startup is missing");
  assert(appJs.includes("!window.__WASM_AGENT_DISABLE_SW__"), "service worker must be disabled for dev HMR");
  assert(devHmrJs.includes("EventSource"), "dev HMR event stream client is missing");
  assert(devHmrJs.includes("/modules/hmr/events"), "dev HMR event endpoint should be namespaced under modules/hmr");
  assert(devHmrJs.includes("HMR_CLIENT_REVISION"), "dev HMR client revision is missing");
  assert(devHmrJs.includes("HMR_REVISION_STORAGE_KEY"), "dev HMR stale revision storage is missing");
  assert(devHmrJs.includes("dev-hmr:revision"), "dev HMR offline revision reload is missing");
  assert(devHmrJs.includes("reloadStylesheets"), "dev HMR stylesheet reload is missing");
  assert(devHmrJs.includes("__wasmAgentDevHmr"), "dev HMR must consult the app before page reloads");
  assert(devHmrJs.includes("requestReload"), "dev HMR deferred reload hook is missing");
  assert(appJs.includes("shouldStartDevHmr"), "dev HMR automatic startup guard is missing");
  assert(appJs.includes("__WASM_AGENT_DISABLE_HMR__"), "dev HMR escape hatch is missing");
  assert(swJs.includes("/modules/hmr/dev-hmr.js"), "service worker cache must use relocated HMR module path");
  assert(swJs.includes("wasm-agent-v33"), "service worker cache revision must invalidate stale client code");
  assert(swJs.includes('/auth/session'), "service worker must not cache auth session reads");
  assert(swJs.includes("/modules/barcode-reader/module.js"), "service worker cache must include image analyzer modules");
  assert(!appJs.includes("WIDGET_LAYOUT_STORAGE_KEY"), "widget layout must be account/space backend state");
  assert(appJs.includes("SPACE_LAYOUT_SCHEMA"), "space layout schema marker is missing");
  assert(appJs.includes("CLIENT_DEVICE_STORAGE_KEY"), "stable client device id persistence is missing");
  assert(appJs.includes('"X-Wasm-Agent-Device-Id"'), "device-local layout requests must identify the client device");
  assert(appJs.includes("USER_EVENT_LIMIT"), "session-only event buffer limit is missing");
  assert(appJs.includes("recordUserEvent"), "observation event recorder is missing");
  assert(appJs.includes("buildObservationSnapshot"), "observation snapshot builder is missing");
  assert(appJs.includes("sendAgentMessage"), "embedded assistant chat sender is missing");
  assert(appJs.includes("formatTurnElapsed"), "embedded assistant elapsed timer formatter is missing");
  assert(appJs.includes("startAgentTurnTimer"), "embedded assistant turn timer startup is missing");
  assert(appJs.includes("agentTurnHeader"), "embedded assistant response header renderer is missing");
  assert(appJs.includes("copyAgentMessageText"), "embedded assistant message copy action is missing");
  assert(appJs.includes("latestNonAgentClick"), "embedded assistant must distinguish workspace clicks from chat clicks");
  assert(appJs.includes("requested_click_context"), "embedded assistant must send explicit click context");
  assert(appJs.includes("updateAgentTokenUsage"), "embedded assistant token usage renderer is missing");
  assert(!appJs.includes("Hermes responded"), "assistant message header should not include response label");
  assert(!appJs.includes("Complete"), "assistant message header should not include completion label");
  assert(indexHtml.includes("agentTokenUsage"), "embedded assistant token usage display is missing");
  assert(appJs.includes("agentTargetNode"), "embedded assistant target node state is missing");
  assert(appJs.includes("renderAgentNodeSelect"), "embedded assistant node selector renderer is missing");
  assert(appJs.includes("target_node: targetNode"), "embedded assistant target node payload is missing");
  assert(!appJs.includes("proposalFromText"), "patch proposal extraction should be removed");
  assert(!appJs.includes("renderPatchProposalCard"), "patch proposal card renderer should be removed");
  assert(appJs.includes("renderAgentDiagnostics"), "embedded assistant diagnostics renderer is missing");
  assert(appJs.includes('["Mode", diagnostics.mode'), "embedded assistant mode diagnostic renderer is missing");
  assert(appJs.includes("renderAgentContextPreview"), "embedded assistant context preview renderer is missing");
  assert(appJs.includes("const mode = els.agentModeSelect.value"), "embedded assistant mode capture is missing");
  assert(appJs.includes("mode,"), "embedded assistant mode payload is missing");
  assert(appJs.includes("AGENT_SESSIONS_STORAGE_KEY"), "embedded assistant session persistence is missing");
  assert(appJs.includes("setAgentBalloon"), "embedded assistant balloon controller is missing");
  assert(appJs.includes("agentSettingsBalloon"), "embedded assistant settings balloon controller is missing");
  assert(appJs.includes('toggleAgentBalloon("settings")'), "embedded assistant settings toggle is missing");
  assert(appJs.includes("agentSessionList"), "embedded assistant session list renderer is missing");
  assert(appJs.includes("statSpan"), "embedded assistant changed-files diff stat renderer is missing");
  assert(appJs.includes("changedFilesFooter"), "embedded assistant changed-files message footer renderer is missing");
  assert(appJs.includes("agentActionsChain"), "embedded assistant action chain renderer is missing");
  assert(appJs.includes("agentActionRowsFromPayload"), "embedded assistant final action event folding is missing");
  assert(appJs.includes("renderAgentImageCards"), "embedded assistant image-card renderer is missing");
  assert(appJs.includes("agent-image-card"), "embedded assistant image-card UI hook is missing");
  assert(appJs.includes("agent-action-row-summary"), "embedded assistant action row summaries are missing");
  assert(appJs.includes("JSON.stringify(action.arguments"), "embedded assistant action argument previews are missing");
  assert(appJs.includes("updateAgentSendButton"), "embedded assistant send button state renderer is missing");
  assert(appJs.includes("stopAgentMessage"), "embedded assistant stop behavior is missing");
  assert(appJs.includes("agentAbortController"), "embedded assistant abort controller is missing");
  assert(appJs.includes("AGENT_IMAGE_MAX_BYTES"), "embedded assistant image compression budget is missing");
  assert(appJs.includes("AGENT_IMAGE_TOTAL_MAX_BYTES"), "embedded assistant aggregate image budget is missing");
  assert(appJs.includes("analyzeImageElement"), "embedded assistant browser-side image analyzer is missing");
  assert(appJs.includes("IMAGE_ANALYZER_CACHE"), "embedded assistant lazy image analyzer cache is missing");
  assert(appJs.includes("IMAGE_CARD_ANALYZER_REVISION"), "embedded assistant image-card analyzer revision is missing");
  assert(appJs.includes("loadImageAnalyzer"), "embedded assistant lazy image analyzer loader is missing");
  assert(appJs.includes("BarcodeDetector"), "embedded assistant barcode detector module is missing");
  assert(appJs.includes("TextDetector"), "embedded assistant native OCR probe is missing");
  assert(appJs.includes("OCR_TESSERACT_DEFAULT_URL"), "embedded assistant Tesseract OCR runtime URL is missing");
  assert(appJs.includes("createTesseractOcrAnalyzer"), "embedded assistant Tesseract OCR analyzer is missing");
  assert(appJs.includes("prepareOcrInput"), "embedded assistant OCR preprocessing is missing");
  assert(appJs.includes("OCR_PREPROCESS_MAX_WIDTH"), "embedded assistant OCR crop scaling budget is missing");
  assert(appJs.includes("tessedit_pageseg_mode"), "embedded assistant OCR page segmentation tuning is missing");
  assert(appJs.includes("SCRIPT_RUNTIME_CACHE"), "embedded assistant external runtime cache is missing");
  assert(appJs.includes("OCR_ANALYZER_TIMEOUT_MS"), "embedded assistant OCR timeout budget is missing");
  assert(appJs.includes("textLikeRegionSignals"), "embedded assistant text-like region heuristic is missing");
  assert(appJs.includes("module_results"), "embedded assistant image-card module results are missing");
  assert(appJs.includes("analyzer_modules"), "embedded assistant image-card analyzer module registry is missing");
  assert(appJs.includes("browser + lazy modules"), "embedded assistant image analysis action must expose lazy modules");
  assert(appJs.includes("hermes.wasm_agent.image_card.v1"), "embedded assistant image card schema is missing");
  assert(appJs.includes("averageHash"), "embedded assistant perceptual hash is missing");
  assert(appJs.includes("brightness_distribution"), "embedded assistant image-card brightness distribution is missing");
  assert(appJs.includes("center_edge_delta"), "embedded assistant image-card center/edge metric is missing");
  assert(appJs.includes("text_like_score"), "embedded assistant image-card text-like score is missing");
  assert(appJs.includes("text_regions"), "embedded assistant image-card text region composition is missing");
  assert(appJs.includes("horizontalSymmetry"), "embedded assistant image-card symmetry metric is missing");
  assert(appJs.includes("smooth gradient-like surface"), "embedded assistant image-card gradient note is missing");
  assert(appJs.includes("Store image assets"), "embedded assistant image store action is missing");
  assert(appJs.includes("Decode pixels"), "embedded assistant decode action is missing");
  assert(appJs.includes("Analyze image"), "embedded assistant analyze action is missing");
  assert(appJs.includes("Build image cards"), "embedded assistant image card action is missing");
  assert(appJs.includes("/agent/attachments"), "embedded assistant attachment store call is missing");
  assert(appJs.includes("agentImageCardPreview"), "embedded assistant image-card action preview is missing");
  assert(appJs.includes("agentPendingAttachmentSummaries"), "embedded assistant summarized attachment queue is missing");
  assert(appJs.includes("clearAgentPendingImages"), "embedded assistant must clear pending images on send");
  assert(appJs.includes("installDevHmrBridge"), "embedded assistant HMR bridge is missing");
  assert(appJs.includes("flushDeferredHmrReload"), "embedded assistant deferred HMR reload flush is missing");
  assert(appJs.includes("newAgentSession"), "embedded assistant new session behavior is missing");
  assert(appJs.includes("installAgentDragging"), "embedded assistant dragging is missing");
  assert(appJs.includes("placeAgentPanel"), "embedded assistant overflow placement is missing");
  assert(appJs.includes("if (nextOpen) {\n    placeAgentPanel();"), "embedded assistant must place panel before first visible frame");
  assert(appJs.includes("clampAgentLayout"), "embedded assistant avatar bounds clamp is missing");
  assert(appJs.includes("agentAvatarSize"), "embedded assistant drag bounds must use avatar size");
  assert(appJs.includes("agentPanelSide"), "embedded assistant panel side latch is missing");
  assert(appJs.includes("leftSideLeft"), "embedded assistant panel must compute left-side placement");
  assert(appJs.includes("rightSideLeft"), "embedded assistant panel right-side fallback is missing");
  assert(appJs.includes('side === "left" && !leftFits && rightFits'), "embedded assistant panel left-to-right switch guard is missing");
  assert(appJs.includes('side === "right" && !rightFits && leftFits'), "embedded assistant panel right-to-left switch guard is missing");
  assert(appJs.includes("panel.style.left"), "embedded assistant panel must use clamped coordinates");
  assert(appJs.includes("appViewportRect"), "embedded assistant must use app viewport bounds");
  assert(appJs.includes("window.visualViewport"), "embedded assistant must use visual viewport bounds");
  assert(appJs.includes("defaultAgentLayout"), "embedded assistant default viewport-corner layout is missing");
  assert(appJs.includes("resetAgentToViewportCorner"), "embedded assistant resize reset is missing");
  assert(appJs.includes("resize\", resetAgentAfterViewportChange"), "embedded assistant must reset on viewport resize");
  assert(stylesCss.includes(".agent-overlay"), "embedded assistant overlay styles are missing");
  assert(stylesCss.includes("width: 58px"), "embedded assistant overlay must match avatar width");
  assert(stylesCss.includes("height: 58px"), "embedded assistant overlay must match avatar height");
  assert(appJs.includes("--agent-app-width"), "embedded assistant app width CSS variable is missing");
  assert(appJs.includes("agentDragSuppressClick"), "embedded assistant drag click suppression is missing");
  assert(appJs.includes("Math.max(minLeft, Math.min(maxLeft, rawLeft))"), "embedded assistant horizontal clamp is missing");
  assert(appJs.includes("Math.max(minTop, Math.min(maxTop, preferredTop))"), "embedded assistant vertical clamp is missing");
  assert(appJs.includes("AGENT_LAYOUT_STORAGE_KEY"), "embedded assistant layout persistence is missing");
  assert(appJs.includes("compactObservation"), "embedded assistant must send compact observation context");
  assert(appJs.includes("AGENT_DEFAULT_MESSAGE_CONTENT"), "embedded assistant seed message constant is missing");
  assert(appJs.includes("agentTranscriptForRequest"), "embedded assistant transcript filter is missing");
  assert(appJs.includes("transcript,"), "embedded assistant must send compact transcript context");
  assert(appJs.includes("Inspecting context"), "embedded assistant inspect status is missing");
  assert(appJs.includes("AbortController"), "bridge calls must have a timeout guard");
  assert(appJs.includes("state.agentTurnTimeoutMs + 5000"), "embedded assistant timeout must follow config");
  assert(appJs.includes("The selected node did not answer within"), "embedded assistant timeout response is missing");
  assert(!appJs.includes("cheap inspect/proposal"), "embedded assistant timeout copy must not mention removed proposal flow");
  assert(appJs.includes("/agent/session/message"), "embedded assistant local session endpoint is missing");
  assert(appJs.includes("/agent/session/message/stream"), "embedded assistant action stream endpoint is missing");
  assert(appJs.includes("ReadableStream"), "embedded assistant streaming action reader is missing");
  assert(appJs.includes("mergeAgentAction"), "embedded assistant streaming action merge is missing");
  assert(appJs.includes("session_id: activeAgentSession().id"), "embedded assistant must send actual session id");
  assert(appJs.includes("observation: compactObservation"), "embedded assistant observation context is missing");
  assert(appJs.includes("describeEventTarget"), "click target descriptor is missing");
  assert(appJs.includes("classes"), "click target class capture is missing");
  assert(appJs.includes('els.app.dataset.panel = userSpacePanel ? "user-space" : panel'), "active panel dataset is missing");
  assert(appJs.includes("ADMIN_PANEL_IDS.has(panel)"), "admin panel route detection is missing");
  assert(appJs.includes('return `/${panel}`'), "panel route mapping is missing");
  assert(appJs.includes("window.history.pushState"), "panel URL history sync is missing");
  assert(appJs.includes("popstate"), "panel back/forward routing is missing");
  assert(appJs.includes('CHAT_QUERY_VALUE = "wasm-agent-chat"'), "wasm-agent-chat URL state is missing");
  assert(appJs.includes("pushUiNavigationLayer"), "universal UI navigation stack is missing");
  assert(appJs.includes("closeTopUiNavigationLayer"), "universal back/Escape close handler is missing");
  assert(appJs.includes("initializeUiNavigationFromUrl"), "direct chat URL normalization is missing");
  assert(appJs.includes("handleAppPopState"), "popstate must route through UI navigation sync");
  assert(appJs.includes('event.key !== "Escape"'), "Escape must close the topmost UI layer");
  assert(appJs.includes("publishObservationSnapshot"), "observation snapshot publisher is missing");
  assert(appJs.includes("/observation/latest"), "observation debug endpoint call is missing");
  assert(appJs.includes("summarizeEventTarget"), "event target summarizer is missing");
  assert(appJs.includes("hermes.space_os.user_event.v1"), "user event schema is missing");
  assert(appJs.includes("hermes.space_os.observation.v1"), "observation schema is missing");
  assert(appJs.includes("workspace.click"), "workspace click analytics are missing");
  assert(appJs.includes("browser.url_submitted"), "browser URL analytics are missing");
  assert(appJs.includes("browser.type_forwarded"), "browser typed action analytics are missing");
  assert(appJs.includes("task.prompt_submitted"), "task analytics are missing");
  assert(appJs.includes("logs.loaded"), "logs analytics are missing");
  assert(!appJs.includes('document.addEventListener("keydown"'), "document-level raw key capture is not allowed");
  assert(appJs.includes('widget.addEventListener("pointerdown"'), "click-to-front behavior is missing");
  assert(appJs.includes("/browser/open"), "browser proof endpoint call is missing");
  assert(appJs.includes("/browser/input"), "interactive browser input endpoint call is missing");
  assert(appJs.includes("/browser/stream"), "browser stream websocket call is missing");
  assert(appJs.includes("openBrowserStream"), "browser stream client is missing");
  assert(appJs.includes("setBrowserUrlInput"), "browser URL input focus guard is missing");
  assert(appJs.includes("browserUrlDraft"), "browser URL draft state is missing");
  assert(appJs.includes("browserAddressValue"), "browser submit draft value is missing");
  assert(appJs.includes("browserPendingUrl"), "pending browser navigation guard is missing");
  assert(appJs.includes('sendBrowserStreamAction("navigate"'), "stream navigation reuse is missing");
  assert(appJs.includes('message.status === "navigating"'), "stream navigation status is missing");
  assert(appJs.includes("browserViewportSize"), "browser viewport fitting is missing");
  assert(appJs.includes("startBrowserLive"), "browser live mode is missing");
  assert(!indexHtml.includes(`${removedWidgetLayerAttr}="front"`), "legacy widget lift buttons should be removed");
  assert(!indexHtml.includes(`${removedWidgetLayerAttr}-target`), "legacy widget dock should be removed");
  assert(!appJs.includes(removedLayerDockState), "legacy widget dock state should be removed");
  assert(indexHtml.includes('data-widget-control="minimize"'), "widget minimize controls are missing");
  assert(indexHtml.includes('data-widget-control="maximize"'), "widget maximize controls are missing");
  assert(appJs.includes("setWidgetMinimized"), "widget minimize behavior is missing");
  assert(appJs.includes("toggleWidgetMaximized"), "widget maximize behavior is missing");
  assert(appJs.includes("defaultWidgetLayoutForPanel"), "user/home spaces need minimized default widget layout");
  assert(appJs.includes("spaceApps"), "space app layer filtering is missing");
  assert(appJs.includes("SPACE_APP_MAPPINGS"), "space app entity mapping is missing");
  assert(appJs.includes('home: ["devices"]'), "Connected Devices must stay mapped to Home by default");
  assert(appJs.includes("widgetAvailableInPanel"), "unmapped widgets must stay hidden from the active space");
  assert(appJs.includes("sanitizeWidgetLayoutForPanel"), "unmapped app layout state must not leak into other spaces");
  assert(appJs.includes('if (widgetId === "devices") return activeSpaceStorageId(panel) === "home";'), "Connected Devices widget must be hard-gated to Home");
  assert(stylesCss.includes('.os-shell:not([data-panel="home"]) .devices-widget'), "Connected Devices must be hidden outside Home even during panel transitions");
  assert(!appJs.includes('{ id: "timeline"'), "Timeline must not be an app-layer icon");
  assert(appJs.includes("FIXED_WIDGET_LAYOUT"), "fixed widget layout defaults are missing");
  assert(appJs.includes("openTimelineFromConfig"), "space config menu must open the active timeline");
  assert(stylesCss.includes(".config-action-button"), "config menu timeline action style is missing");
  assert(indexHtml.includes("configModalSpaceName"), "space config must show the active space name");
  assert(indexHtml.includes("spaceBoard"), "scrollable space board is missing");
  assert(appJs.includes("setCanvasDensity"), "space config density control is missing");
  assert(appJs.includes('label.textContent = "Space density"'), "canvas density label must be renamed to space density");
  assert(appJs.includes("installDensityDial"), "space density must use a draggable line");
  assert(appJs.includes("CANVAS_DENSITY_MAX = 10"), "space density must scale to the 10x local canvas ceiling");
  assert(appJs.includes('dial.setAttribute("aria-valuemax", String(CANVAS_DENSITY_MAX))'), "density slider max must follow the canvas ceiling");
  assert(appJs.includes("config-density-line"), "space density line markup is missing");
  assert(stylesCss.includes(".config-density-line"), "space density line styles are missing");
  assert(!stylesCss.includes("conic-gradient"), "space density control should be a simple line, not a circle");
  assert(!stylesCss.includes(".config-density-control button"), "space density must not render step buttons");
  assert(!appJs.includes('label.textContent = "Canvas density"'), "legacy canvas density label must not render");
  assert(appJs.includes("freezeWidgetPixelLayout"), "space density changes must freeze widget pixel geometry first");
  assert(appJs.includes("widthPx") && appJs.includes("heightPx"), "widget geometry must preserve pixel dimensions");
  assert(appJs.includes("installSpacePanning"), "space canvas click-drag panning is missing");
  assert(appJs.includes("isPrimaryPointer"), "touch-safe pointer handling is missing");
  assert(appJs.includes("viewport.setPointerCapture"), "mobile canvas panning must capture the touch pointer");
  assert(appJs.includes('viewport.addEventListener("pointermove", move, { passive: false })'), "canvas panning must listen on the captured viewport");
  assert(appJs.includes("viewport.releasePointerCapture"), "canvas panning must release pointer capture");
  assert(indexHtml.includes("spaceMiniMap"), "canvas panning minimap host is missing");
  assert(appJs.includes("renderSpaceMiniMap"), "canvas panning minimap renderer is missing");
  assert(appJs.includes("setSpaceMiniMapVisible(true)"), "canvas panning must reveal the minimap while dragging");
  assert(appJs.includes("is-minimap-suppressed"), "space config button must fade while the panning minimap is visible");
  assert(appJs.includes("space-minimap-entity"), "canvas panning minimap must render entity miniatures");
  assert(appJs.includes("miniMapAppEntityFromButton"), "minimap app markers must come from minimized app state");
  assert(appJs.includes("layout.minimized === false"), "minimap should not duplicate an opened app icon over its widget footprint");
  assert(appJs.includes('button.querySelector?.(".space-app-icon")'), "minimap app markers must use actual app icon geometry");
  assert(stylesCss.includes(".space-minimap"), "canvas panning minimap styles are missing");
  assert(stylesCss.includes("--space-minimap-max-width: 184px;"), "canvas panning minimap must define a desktop max width");
  assert(stylesCss.includes(".space-minimap {\n  --space-minimap-max-width: 184px;\n  --space-minimap-max-height: 112px;\n  position: absolute;\n  right: 8px;\n  top: 8px;\n  z-index: 10020;"), "canvas panning minimap must occupy the config button anchor above home actions");
  assert(appJs.includes("SPACE_MINIMAP_PADDING_PX"), "minimap must wrap its mapped canvas with a small stable padding");
  assert(appJs.includes("map.style.width = `${Math.round(plot.mapWidth)}px`;"), "minimap outer rectangle must shrink-wrap the mapped canvas");
  assert(stylesCss.includes(".space-minimap-viewport"), "canvas panning minimap viewport marker is missing");
  assert(stylesCss.includes(".space-minimap-viewport {\n  position: absolute;\n  box-sizing: border-box;"), "minimap viewport border must remain visible at board edges");
  assert(stylesCss.includes(".space-minimap-viewport {\n  position: absolute;\n  box-sizing: border-box;\n  display: block;\n  border: 1px solid rgba(237, 245, 255, 0.92);\n  border-radius: 1px;"), "minimap viewport border radius should stay close to the scaled canvas geometry");
  assert(appJs.includes("visibleBoardRect(metrics)"), "minimap viewport marker must be derived from the actual visible board rect");
  assert(appJs.includes("viewportRect,"), "minimap metrics must capture the scroll container rect");
  assert(appJs.includes("metrics.viewport.scrollLeft"), "minimap viewport must use density-aware scroll coordinates");
  assert(appJs.includes("rect.left - metrics.viewportRect.left + metrics.viewport.scrollLeft"), "minimap entities must use the same scroll coordinate space as the viewport");
  assert(appJs.includes("miniMapPlotMetrics(metrics, mapWidth, mapHeight)"), "minimap entities and viewport must share the same inner plot projection");
  assert(appJs.includes("miniMapProjectRect(visibleRect, plot)"), "minimap viewport must use the same projection helper as entities");
  assert(appJs.includes("miniMapProjectAppMarker(entity, plot, visibleRect)"), "minimap app markers must be projected from icon footprints");
  assert(appJs.includes("boardRectContains(visibleRect, entity)"), "fully visible app markers must stay inside the minimap viewport marker");
  assert(appJs.includes("const size = clamp(footprintSize, 2, 6);"), "minimap app marker size must stay relative to the projected icon footprint");
  assert(appJs.includes('miniMapEntityFromElement(icon || button, metrics, "app", boardBounds)'), "minimap app markers must use the painted app icon rectangle");
  assert(appJs.includes("miniMapEntityFromElement(element, metrics, kind, boardBounds)"), "minimap entities must be clipped to the board bounds");
  assert(appJs.includes("miniMapProjectRect(entity, plot, 5, 4)"), "minimap widget miniatures must be scaled into minimap coordinates");
  assert(appJs.includes("miniMapEntityClassName"), "minimap entities must avoid global app/widget class collisions");
  assert(appJs.includes('classes.push("is-widget")'), "minimap widget entities must use a namespaced widget class");
  assert(!appJs.includes("item.className = `space-minimap-entity ${entity.kind}`"), "minimap entities must not receive the global widget class");
  assert(stylesCss.includes(".space-minimap-entity.is-widget"), "minimap widget class style is missing");
  assert(!stylesCss.includes(".space-minimap-entity.app"), "minimap app selector must be namespaced");
  assert(stylesCss.includes(".space-config-button.is-minimap-suppressed"), "space config button fade style is missing");
  assert(appJs.includes("spaceMiniMapCanRender"), "minimap must stay hidden when the board is not pannable");
  assert(appJs.includes("ensureOpenedWidgetContained"), "offscreen opened widgets must move to the canvas initial point");
  assert(stylesCss.includes(".space-viewport.is-panning"), "space canvas panning style is missing");
  assert(stylesCss.includes("scrollbar-width: none;"), "space viewport native scrollbar should be hidden");
  assert(stylesCss.includes(".space-viewport.can-scroll-right"), "space viewport needs a right navigation affordance");
  assert(stylesCss.includes(".space-viewport::-webkit-scrollbar"), "webkit space viewport scrollbar hiding is missing");
  assert(appJs.includes("updateSpaceNavigationHints"), "space viewport navigation affordance updater is missing");
  assert(stylesCss.includes('@media (max-width: 1120px) {\n  .space-frame {\n    grid-template-columns: 1fr;\n    grid-template-rows: minmax(620px, 1fr) 360px;\n  }\n\n  .os-shell[data-panel="home"] .space-frame,\n  .os-shell[data-panel="admin"] .space-frame,\n  .os-shell[data-panel="user-space"] .space-frame {\n    grid-template-columns: minmax(0, 1fr) 0;\n    grid-template-rows: minmax(0, 1fr);\n  }'), "home/admin/user spaces must not keep a hidden side-panel row that skews minimap viewport height");
  assert(stylesCss.includes('@media (max-width: 820px)') && stylesCss.includes('.os-shell[data-panel="home"] .space-frame,\n  .os-shell[data-panel="admin"] .space-frame,\n  .os-shell[data-panel="user-space"] .space-frame {\n    grid-template-rows: minmax(0, 1fr);\n  }'), "admin mobile space frame must use the actual visible canvas row for minimap math");
  assert(stylesCss.includes("left: clamp(6px, var(--density-progress), calc(100% - 6px));"), "density line knob must stay within the track bounds");
  assert(!stylesCss.includes("left: var(--density-progress);"), "density line knob must not center itself beyond the track edges");
  assert(stylesCss.includes("right: 8px"), "space config button should stick to the space top-right corner");
  assert(stylesCss.includes(".space-config-button {\n  position: absolute;\n  right: 8px;\n  top: 8px;\n  z-index: 10020;"), "space config button should layer above home actions");
  assert(stylesCss.includes("overflow: hidden;") && stylesCss.includes("overflow: auto;"), "shell must be fixed while space viewport scrolls");
  assert(appJs.includes("fitWidgetToVisibleViewport"), "opened widgets must be fit to the visible canvas on mobile");
  assert(appJs.includes("workspace.widget_visible_bounds_applied"), "visible widget bounds adjustment event is missing");
  assert(stylesCss.includes("width: min(344px, calc(100dvw - 100px));"), "mobile widgets must size against the visible device viewport, not the density board");
  assert(stylesCss.includes(".os-shell[data-mobile-launcher=\"top\"] .devices-widget"), "mobile top-launcher widget width override is missing");
  assert(!appJs.includes('metric("Space"'), "space config options should not render a duplicate Space card");
  assert(appJs.includes("activeSpaceTitle"), "active space title rendering is missing");
  assert(appJs.includes("space-home") && appJs.includes("space-admin"), "home/admin space names are missing");
  assert(appJs.includes("APP_ICON_GRID_PX"), "app icon snap grid constant is missing");
  assert(appJs.includes("nearestOpenAppPosition"), "app icons must snap to a non-overlapping grid position");
  assert(appJs.includes("appLeftPx"), "app icon placement must preserve pixel position across resize");
  assert(appJs.includes("setWidgetMinimized(app.id, !layout.minimized)"), "app icons must toggle open/minimized widget state");
  assert(stylesCss.includes(".app-layer::before"), "app icon grid layer is missing");
  assert(appJs.includes("showAppContextMenu"), "app/widget right-click menu handler is missing");
  assert(appJs.includes("installLongPressMenu"), "mobile long-press menu support is missing");
  assert(appJs.includes("openAppEditModal"), "app/widget edit form controller is missing");
  assert(appJs.includes("widgetDimensionBounds"), "app/widget dimension bounds editor is missing");
  assert(stylesCss.includes(".app-context-menu"), "app/widget context menu styles are missing");
  assert(stylesCss.includes(".edit-form"), "app/widget edit form styles are missing");
  assert(appJs.includes("LAUNCHER_PREF_STORAGE_KEY"), "mobile launcher preference persistence is missing");
  assert(appJs.includes("renderLauncherPreferenceControl"), "space-home config launcher preference control is missing");
  assert(stylesCss.includes(".config-toggle-row"), "launcher preference config row styles are missing");
  assert(appJs.includes("installModalBackdropDismiss"), "modal backdrop dismissal must respect inside-to-outside text selection");
  assert(appJs.includes("installAgentPanelDragging"), "assistant panel header dragging is missing");
  assert(!appJs.includes("agentPanelManual"), "assistant chat panel must stay anchored to the avatar");
  assert(appJs.includes("moveAgentGroupFromPanelRect"), "assistant panel drag must keep the chat rect as the main drag object");
  assert(appJs.includes("Moved embedded assistant avatar and chat together"), "assistant panel drag must move the anchored group");
  assert(indexHtml.includes("Minimize wasm-agent-chat"), "chat close button must be labeled as minimize");
  assert(!stylesCss.includes(".agent-icon-close::after"), "chat minimize icon must not render an x");
  assert(appJs.includes("RESOURCE_POLL_MS"), "resource monitor realtime polling is missing");
  assert(appJs.includes('metric("RAM"'), "Memory must be labeled as RAM");
  assert(appJs.includes('metric("Nodes"'), "resource monitor node count row is missing");
  assert(appJs.includes("compactGb(diskUsed)"), "Disk compact used/total display is missing");
  assert(stylesCss.includes("height: auto;"), "resource monitor default height should fit content");
  assert(stylesCss.includes(".resources-widget .metric-grid"), "resource monitor must list metrics top-down");
  assert(indexHtml.includes("widget-resize-handle"), "widget resize handle is missing");
  assert(appJs.includes("installWidgetResizing"), "widget resize behavior is missing");
  assert(!appJs.includes("!isPrimaryPointer(event) || isCompactViewport()"), "widget resizing must remain available on mobile");
  assert(appJs.includes('handle.addEventListener("pointermove", move, { passive: false })'), "widget resize must use touch-safe pointer movement");
  assert(appJs.includes("runNodeAction"), "node action bridge calls are missing");
  assert(appJs.includes("bridgeActionResult"), "node action result unwrapping is missing");
  assert(appJs.includes("restart_node"), "lifecycle action rendering is missing");
  assert(appJs.includes("window.confirm"), "destructive action confirmation is missing");
  assert(appJs.includes("action.payload_template"), "bridge action payload templates are not reused");
  assert(indexHtml.includes("nodeList"), "node action list host is missing");
  assert(indexHtml.includes("nodeContextMenu"), "topology node context menu host is missing");
  assert(appJs.includes("showNodeContextMenu"), "topology node right-click actions are missing");
  assert(appJs.includes("openNodeEditModal"), "topology node edit modal controller is missing");
  assert(appJs.includes("nodeModelOverrides"), "topology node model override persistence is missing");
  assert(appJs.includes("installTopologyNodeDragging"), "topology nodes must be repositionable");
  assert(appJs.includes("statusClass"), "topology node status classes are missing");
  assert(indexHtml.includes('data-widget-id="devices"'), "home connected devices app widget is missing");
  assert(indexHtml.includes("devicesSyncButton"), "connected devices sync button is missing");
  assert(appJs.includes('id: "devices"'), "connected devices app definition is missing");
  assert(appJs.includes('fetchJson("/account/devices"'), "connected devices app must load account devices");
  assert(appJs.includes('fetchJson("/account/devices/sync"'), "connected devices sync installer endpoint call is missing");
  assert(appJs.includes('fetchJson("/account/devices/main"'), "connected devices main-device switch endpoint call is missing");
  assert(appJs.includes("setMainDevice"), "connected devices main-device switch handler is missing");
  assert(appJs.includes("ensureMainDeviceForEvolution"), "main-device offline guard for artifact evolution is missing");
  assert(stylesCss.includes(".device-main-button"), "connected devices main-device icon styles are missing");
  assert(serverPy.includes("create_device_sync_package"), "connected devices sync package backend is missing");
  assert(serverPy.includes("hermes.wasm_agent.device_sync_package.v1"), "connected devices sync package schema is missing");
  assert(serverPy.includes("/account/devices/main"), "connected devices main-device endpoint is missing");
  assert(serverPy.includes("set_main_account_device"), "connected devices main-device backend is missing");
  assert(serverPy.includes("DEVICE_ONLINE_WINDOW_SEC"), "connected devices online window is missing");
  assert(appJs.includes("deviceOsGlyph"), "connected devices must show an OS icon");
  assert(serverPy.includes("/account/devices"), "account devices endpoint is missing");
  assert(serverPy.includes("list_account_devices"), "account devices listing backend is missing");
  assert(indexHtml.includes("homeArtifactsButton"), "Home Artifacts button is missing");
  assert(indexHtml.includes("artifactsModal"), "Artifacts inventory modal is missing");
  assert(appJs.includes("renderArtifacts"), "Artifacts inventory renderer is missing");
  assert(stylesCss.includes(".artifact-list"), "Artifacts inventory styles are missing");
  assert(appJs.includes('fetchJson("/storage/export"'), "storage export client action is missing");
  assert(appJs.includes('fetchJson("/storage/import"'), "storage import client action is missing");
  assert(serverPy.includes("/storage/export"), "storage export endpoint is missing");
  assert(serverPy.includes("/storage/import"), "storage import endpoint is missing");
  assert(serverPy.includes("available_bytes"), "storage payload must include local disk availability");
  assert(serverPy.includes('"device-layouts"'), "device-local layout root is missing");
  assert(serverPy.includes("user_space_layout_path"), "device-local space layout path helper is missing");
  assert(serverPy.includes("device_layouts"), "storage export/import must include device-local layout backups");
  assert(artifactsMd.includes("hermes.wasm_agent.artifact.v1"), "wasm artifact manifest design note is missing");
  assert(artifactsMd.includes("device-local"), "artifact design must keep layout device-local");
  assert(artifactsMd.includes("marketplace"), "artifact design must document marketplace direction");
  assert(artifactsMd.includes("component runtime"), "artifact design must document component runtime entry points");
  assert(serverPy.includes("DEFAULT_BROWSER_STREAM_FPS"), "browser stream throttle default is missing");
  assert(serverPy.includes("save_observation"), "observation snapshot persistence is missing");
  assert(serverPy.includes("latest_observation"), "observation snapshot read endpoint is missing");
  assert(serverPy.includes("serve_dev_hmr_events"), "dev HMR event endpoint is missing");
  assert(serverPy.includes("/modules/hmr/events"), "dev HMR backend endpoint should be namespaced under modules/hmr");
  assert(serverPy.includes("text/event-stream"), "dev HMR endpoint must use SSE");
  assert(serverPy.includes("dev_hmr_revision"), "dev HMR backend revision fingerprint is missing");
  assert(serverPy.includes("hmr_client_stale"), "dev HMR legacy-client reload event is missing");
  assert(serverPy.includes("agentTurnTimeoutSec"), "embedded assistant timeout config is missing");
  assert(serverPy.includes("HERMES_WASM_AGENT_CHAT_TIMEOUT_SEC"), "embedded assistant timeout env is missing");
  assert(serverPy.includes("embedded_agent_message"), "embedded agent session adapter is missing");
  assert(serverPy.includes("stream_embedded_agent_message"), "embedded agent stream adapter is missing");
  assert(serverPy.includes("application/x-ndjson"), "embedded agent stream should use NDJSON");
  assert(serverPy.includes("/agent/session/message/stream"), "embedded agent stream route is missing");
  assert(serverPy.includes('{"auto", "local", "bridge"}'), "embedded agent modes are missing");
  assert(serverPy.includes("deterministic_agent_reply"), "embedded agent deterministic fallback is missing");
  assert(serverPy.includes("real patch"), "embedded agent cheap proposal trigger is missing");
  assert(serverPy.includes("Implementation brief:"), "embedded agent local implementation brief response is missing");
  assert(serverPy.includes("context_estimated_tokens"), "embedded agent context estimate is missing");
  assert(serverPy.includes("token_usage"), "embedded agent exact token usage diagnostic is missing");
  assert(serverPy.includes("current_turn_observation"), "embedded agent current-turn observation tool is missing");
  assert(serverPy.includes("last_non_agent_click"), "embedded agent click context must ignore chat controls");
  assert(serverPy.includes("context_preview"), "embedded agent context preview is missing");
  assert(serverPy.includes("agent_action_events"), "embedded agent action events are missing");
  assert(serverPy.includes("tool_action_label"), "embedded agent rich tool action labels are missing");
  assert(serverPy.includes("tool_action_preview"), "embedded agent rich tool action previews are missing");
  assert(serverPy.includes("Receive final reply"), "embedded agent final reply action is missing");
  assert(serverPy.includes("compact_agent_images"), "embedded agent image compaction guard is missing");
  assert(serverPy.includes("save_agent_attachment"), "embedded agent attachment asset store is missing");
  assert(serverPy.includes("serve_agent_attachment"), "embedded agent attachment asset serving is missing");
  assert(serverPy.includes("/auth/google"), "Google auth endpoint is missing");
  assert(serverPy.includes("/auth/session"), "auth session endpoint is missing");
  assert(serverPy.includes("CREATE TABLE IF NOT EXISTS user_tb"), "user_tb account table is missing");
  assert(serverPy.includes("next_snowflake_id"), "Snowflake user id generator is missing");
  assert(serverPy.includes("state\" / \"db\" / \"sqlite\" / \"wa_db.sqlite3"), "wasm-agent account DB path is missing");
  assert(serverPy.includes("GOOGLE_LOGIN_CLIENT_ID"), "wa.env Google login client id config is missing");
  assert(serverPy.includes("HERMES_WASM_AGENT_GOOGLE_CLIENT_ID"), "Google client id config env is missing");
  assert(!serverPy.includes("path=DEFAULT_AUTH_ENV_PATH"), "wasm-agent auth must not depend on orchestrator.env");
  assert(serverPy.includes("DEFAULT_WA_ENV_PATH"), "wa.env config path is missing");
  assert(serverPy.includes("ADMIN_EMAIL"), "admin email must be read from wa.env/env");
  assert(serverPy.includes("USER_EMAILS"), "standard user allowlist must be read from wa.env");
  assert(serverPy.includes("is_allowed_account_email"), "auth must allow admins and explicitly allowlisted users only");
  assert(serverPy.includes("google_account_not_allowed"), "unlisted Google accounts must be rejected");
  assert(serverPy.includes('ch in {"-", "_"}'), "space id sanitizer must preserve frontend underscore ids");
  assert(serverPy.includes("ensure_user_quota"), "standard user writes must enforce the storage quota");
  assert(serverPy.includes("is_public_request"), "server auth route gate is missing");
  assert(serverPy.includes("auth_required"), "protected routes must reject unauthenticated requests");
  assert(serverPy.includes('"/admin"'), "admin app route must serve the login shell before auth");
  assert(serverPy.includes('"/space"'), "legacy space app route must serve the login shell before auth");
  assert(serverPy.includes('"/logs"'), "admin log panel route must serve the login shell before auth");
  assert(serverPy.includes('"/timeline"'), "admin timeline panel route must serve the login shell before auth");
  assert(serverPy.includes("signed_auth_value"), "auth session cookies must be signed");
  assert(serverPy.includes("HERMES_WASM_AGENT_AUTH_SECRET"), "auth signing secret override is missing");
  assert(serverPy.includes("DEFAULT_AGENT_ATTACHMENT_MAX_BYTES"), "embedded agent attachment store budget is missing");
  assert(serverPy.includes("DEFAULT_AGENT_ATTACHMENT_STORE_MAX_BYTES"), "embedded agent attachment store total budget is missing");
  assert(serverPy.includes("HERMES_WASM_AGENT_ATTACHMENT_STORE_MAX_BYTES"), "embedded agent attachment store byte limit env is missing");
  assert(serverPy.includes("HERMES_WASM_AGENT_ATTACHMENT_STORE_MAX_FILES"), "embedded agent attachment store file limit env is missing");
  assert(serverPy.includes("HERMES_WASM_AGENT_ATTACHMENT_MAX_AGE_SEC"), "embedded agent attachment store age limit env is missing");
  assert(serverPy.includes("prune_agent_attachments"), "embedded agent attachment retention pruning is missing");
  assert(serverPy.includes("hermes.wasm_agent.attachment_retention.v1"), "embedded agent attachment retention schema is missing");
  assert(serverPy.includes("hermes.wasm_agent.attachment_asset.v1"), "embedded agent attachment asset schema is missing");
  assert(serverPy.includes("hermes.wasm_agent.image_card.v1"), "embedded agent image card schema is missing");
  assert(serverPy.includes("plan_bridge_attachments"), "embedded agent bridge attachment budget planner is missing");
  assert(serverPy.includes("attachment_manifest"), "embedded agent attachment manifest action is missing");
  assert(serverPy.includes("image_card_count"), "embedded agent image card manifest count is missing");
  assert(serverPy.includes("DEFAULT_AGENT_BRIDGE_REQUEST_BYTES"), "embedded agent bridge request budget is missing");
  assert(serverPy.includes("HERMES_WASM_AGENT_FORWARD_IMAGE_URLS"), "embedded agent image_url forwarding opt-in is missing");
  assert(serverPy.includes("bridge_image_url_forwarding_disabled"), "embedded agent must default to text-only attachment manifests");
  assert(serverPy.includes("model_tokens_avoided"), "embedded agent token avoidance diagnostic is missing");
  assert(serverPy.includes("agent_read_file"), "embedded agent read_file tool is missing");
  assert(serverPy.includes("agent_search"), "embedded agent search tool is missing");
  assert(serverPy.includes("agent_git_status"), "embedded agent git_status tool is missing");
  assert(serverPy.includes("changed_files_between_trees"), "embedded agent per-turn changed-files reporting is missing");
  assert(serverPy.includes("safe_worktree_tree_sha"), "embedded agent worktree before/after snapshots are missing");
  assert(serverPy.includes("target_node"), "embedded agent target-node routing is missing");
  assert(serverPy.includes("agent_doctor"), "embedded agent doctor tool is missing");
  assert(serverPy.includes("bridge_proxy"), "same-origin bridge proxy is missing");
  assert(appJs.includes('return fetchJson(`/bridge${path}`'), "client bridge calls must use same-origin proxy");
  assert(serverPy.includes("timeline_status"), "timeline status endpoint is missing");
  assert(serverPy.includes("timeline_checkpoint"), "timeline checkpoint endpoint is missing");
  assert(serverPy.includes("timeline_auto_checkpoint"), "automatic timeline checkpointing is missing");
  assert(serverPy.includes("wasm-agent chat on"), "agent run auto checkpoint subject is missing");
  assert(serverPy.includes("auto-latest.json"), "automatic checkpoint fingerprint state is missing");
  assert(serverPy.includes("refs/wasm-agent-timeline"), "timeline refs namespace is missing");
  assert(serverPy.includes("GIT_INDEX_FILE"), "timeline checkpoints must use a temporary git index");
  assert(serverPy.includes("commit-tree"), "timeline checkpoints must create git commit objects");
  assert(serverPy.includes("agent_app_map"), "embedded agent app map tool is missing");
  assert(serverPy.includes("agent_git_diff_stat"), "embedded agent diff stat tool is missing");
  assert(serverPy.includes("agent_timeline_status"), "embedded agent timeline status tool is missing");
  assert(serverPy.includes('"tool": "timeline_status"'), "embedded agent timeline status preview is missing");
  assert(serverPy.includes("compact_transcript"), "embedded agent transcript compaction is missing");
  assert(serverPy.includes("current_message"), "embedded agent transcript must drop duplicated current user message");
  assert(serverPy.includes("bridge_image_card"), "embedded agent auto image-card bridge answer is missing");
  assert(serverPy.includes("redact_image_card_focus_tools"), "embedded agent image-card bridge filename redaction is missing");
  assert(serverPy.includes("local_image_card_fallback"), "embedded agent image-card fallback is missing");
  assert(serverPy.includes("asks_about_attached_image"), "embedded agent image-card question detector is missing");
  assert(serverPy.includes("image_card_focus"), "embedded agent image-card bridge prompt focus is missing");
  assert(serverPy.includes("brightness_distribution"), "embedded agent image-card composition prompt is missing");
  assert(serverPy.includes("composition"), "embedded agent image-card composition passthrough is missing");
  assert(serverPy.includes("compact_image_evidence"), "embedded agent image-card evidence compaction is missing");
  assert(serverPy.includes("server_enrich_stale_image_card"), "embedded agent stale image-card server fallback is missing");
  assert(serverPy.includes("server-image-card-core"), "embedded agent server image-card evidence module is missing");
  assert(serverPy.includes("browser_image_card_missing_scene_shape_hints"), "embedded agent current image-card server hints fallback is missing");
  assert(serverPy.includes("server_scene_hints"), "embedded agent scene hint classifier is missing");
  assert(serverPy.includes("printed_object_or_label_likelihood"), "embedded agent printed-object scene hint is missing");
  assert(serverPy.includes("server_shape_hints"), "embedded agent shape hint classifier is missing");
  assert(serverPy.includes("cylindrical_surface_likelihood"), "embedded agent cylindrical surface hint is missing");
  assert(serverPy.includes("module_results"), "embedded agent image-card module results passthrough is missing");
  assert(serverPy.includes("analyzer_modules"), "embedded agent image-card analyzer module passthrough is missing");
  assert(serverPy.includes("distinguish detected, not_detected, disabled, unsupported, not_loaded, timeout, and error"), "embedded agent image-card analyzer provenance prompt is missing");
  assert(serverPy.includes("text_like_score"), "embedded agent image-card text-like prompt is missing");
  assert(serverPy.includes("Only quote OCR text when an OCR evidence item has status detected"), "embedded agent OCR evidence rule is missing");
  assert(serverPy.includes("OCR text is evidence for readable words only"), "embedded agent OCR object-identity guard is missing");
  assert(serverPy.includes("prefer wording like printed label/markings on a photographed object"), "embedded agent physical label wording rule is missing");
  assert(serverPy.includes("rounded container or cylindrical surface"), "embedded agent rounded-container wording rule is missing");
  assert(serverPy.includes("There is no vision_analyze tool"), "embedded agent fake vision tool guard is missing");
  assert(serverPy.includes("stale image-card runtime"), "embedded agent stale analyzer revision guard is missing");
  assert(serverPy.includes("filename and local_url are not visual evidence"), "embedded agent image-card anti-hallucination rule is missing");
  assert(serverPy.includes("shape hints are not object identity"), "embedded agent image-card shape identity guard is missing");
  assert(serverPy.includes("file bookkeeping"), "embedded agent image-card filename citation guard is missing");
  assert(serverPy.includes("implementation brief"), "embedded agent evolution prompt is missing");
  assert(serverPy.includes("DEFAULT_BROWSER_SESSION_TTL_SEC"), "browser session TTL default is missing");
  assert(serverPy.includes("HERMES_WASM_AGENT_BROWSER_SESSION_TTL_SEC"), "browser session TTL env is missing");
  assert(serverPy.includes("Page.stopScreencast"), "navigation screencast pause is missing");
  assert(serverPy.includes("send_snapshot_frame"), "post-navigation stream snapshot is missing");
  assert(serverPy.includes("browser_stream_every_nth_frame"), "CDP frame sampling is missing");
  assert(imageCardGoldenPy.includes("synthetic_mug_photo_bytes"), "image-card golden fixture generator is missing");
  assert(imageCardGoldenPy.includes("image-card-text-v2+server-hints"), "image-card golden must assert current-card server hints");
  assert(imageCardGoldenPy.includes("cylindrical_surface_likelihood"), "image-card golden must assert shape hints");
  assert(imageCardGoldenPy.includes("text_like_score"), "image-card golden must assert text-like signal");
  assert(imageCardGoldenPy.includes("attachment_retention_test"), "image-card golden must cover attachment retention");
  assert(imageCardGoldenPy.includes("attachment_save_test"), "image-card golden must cover attachment save metadata");
  assert(doctorSh.includes("image_card_golden.test.py"), "doctor must run image-card golden test");
  assert(!appJs.includes(removedFrameLabel), "space canvas label code should be removed");
  assert(!appJs.includes("requestAnimationFrame(drawCanvas)"), "space canvas should not animate continuously");
  assert(!indexHtml.includes(removedFrameLabel), "space canvas label markup should be removed");
  assert(stylesCss.includes('[data-panel="home"]'), "homespace empty-state CSS is missing");
  console.log("wasm-agent smoke ok");
})().catch((error) => {
  console.error(error);
  process.exit(1);
});
