#!/usr/bin/env python3
"""Check durable context docs against docs/context/ACTIVE_STATE.json."""

from __future__ import annotations

import argparse
import json
import re
import sys
import tempfile
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[2]
STATE_PATH = ROOT / "docs/context/ACTIVE_STATE.json"
REPORT_PATH = ROOT / "reports/context/latest/context-sync-result.json"
GENERATED_DOCS = [
    "README.md",
    "docs/context/MAP.md",
    "native/windows/README.md",
    "plugins/wasm-agent/README.md",
]
NEXT_HEADINGS = {
    "next",
    "next action",
    "durable next actions",
    "durable next step",
    "current goal",
    "current active goal",
}
HISTORICAL_MARKERS = (
    "stale",
    "historical",
    "superseded",
    "implemented-unverified",
    "deprecated",
)
NEXT_STALE_MARKERS = ("stale", "historical", "superseded", "deprecated")
GUARD_NEEDLES = ("installed Windows shell proof", "prove-hot-shell.py", "installed app")


@dataclass
class Drift:
    classification: str
    path: str
    line: int
    message: str

    def as_dict(self) -> dict[str, Any]:
        return {
            "classification": self.classification,
            "path": self.path,
            "line": self.line,
            "message": self.message,
        }


def rel(path: Path) -> str:
    try:
        return str(path.relative_to(ROOT))
    except ValueError:
        return str(path)


def load_state(path: Path = STATE_PATH) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def read_doc(path: Path) -> str:
    return path.read_text(encoding="utf-8") if path.exists() else ""


def line_of(text: str, needle: str) -> int:
    index = text.find(needle)
    if index < 0:
        return 1
    return text.count("\n", 0, index) + 1


def line_has_marker(line: str) -> bool:
    lowered = line.lower()
    return any(marker in lowered for marker in HISTORICAL_MARKERS)


def next_line_has_marker(line: str) -> bool:
    lowered = line.lower()
    return any(marker in lowered for marker in NEXT_STALE_MARKERS)


def section_name(line: str) -> str | None:
    match = re.match(r"^\s{0,3}#{1,6}\s+(.+?)\s*$", line)
    if not match:
        return None
    title = re.sub(r"[`*_#]+", "", match.group(1)).strip().lower()
    return title


def next_section_lines(text: str) -> set[int]:
    active_level: int | None = None
    active = False
    lines: set[int] = set()
    for number, line in enumerate(text.splitlines(), start=1):
        heading = re.match(r"^\s{0,3}(#{1,6})\s+(.+?)\s*$", line)
        if heading:
            level = len(heading.group(1))
            title = section_name(line)
            if active and active_level is not None and level <= active_level:
                active = False
                active_level = None
            if title in NEXT_HEADINGS:
                active = True
                active_level = level
        if active:
            lines.add(number)
    return lines


def generated_block(state: dict[str, Any]) -> str:
    proof_lines = "\n".join(f"{idx}. `{cmd}`" for idx, cmd in enumerate(state["canonicalProofOrder"], start=1))
    capabilities = ", ".join(f"`{item}`" for item in state["requiredWindowsHotShellCapabilities"])
    guards = "\n".join(f"- {guard}" for guard in state["proofGuards"])
    return f"""<!-- BEGIN ACTIVE_STATE -->
<!-- This block is generated by tools/context/check-context-sync.py --fix. -->
**Active goal:** {state["activeGoal"]}

**Canonical proof order:**

{proof_lines}

**Windows hot-op shell protocol:** `shellProtocolVersion: {state["protocols"]["shellProtocolVersion"]}`, `hotOpsProtocolVersion: {state["protocols"]["hotOpsProtocolVersion"]}`

**Required shell capabilities:** {capabilities}

**Hermes wake question:** {state["currentHermesWakeQuestion"]}

**Proof guards:**

{guards}
<!-- END ACTIVE_STATE -->"""


def replace_generated_block(text: str, block: str) -> tuple[str, bool]:
    pattern = re.compile(r"<!-- BEGIN ACTIVE_STATE -->.*?<!-- END ACTIVE_STATE -->", re.S)
    if not pattern.search(text):
        return text, False
    return pattern.sub(block, text, count=1), True


def canonical_order_present(text: str, commands: list[str]) -> bool:
    cursor = 0
    for command in commands:
        found = text.find(command, cursor)
        if found < 0:
            return False
        cursor = found + len(command)
    return True


def check_docs(state: dict[str, Any], root: Path = ROOT, include_generated_block: bool = True) -> list[Drift]:
    drifts: list[Drift] = []
    docs = [root / item for item in state["ownedDocs"]]
    texts = {item: read_doc(root / item) for item in state["ownedDocs"]}

    for item in state["ownedDocs"]:
        path = root / item
        if not path.exists():
            drifts.append(Drift("context_stale_pattern", item, 1, "owned doc is missing"))

    if include_generated_block:
        for item in GENERATED_DOCS:
            text = texts.get(item, read_doc(root / item))
            if "<!-- BEGIN ACTIVE_STATE -->" not in text or "<!-- END ACTIVE_STATE -->" not in text:
                drifts.append(Drift("context_missing_generated_block", item, 1, "missing generated ACTIVE_STATE block; run with --fix after adding markers or add the block manually"))

    has_root_order = any(canonical_order_present(texts.get(item, ""), state["canonicalProofOrder"]) for item in ("README.md", "docs/context/MAP.md"))
    if not has_root_order:
        drifts.append(Drift("context_missing_canonical_proof_order", "README.md", 1, "canonical proof order missing from README.md or docs/context/MAP.md"))
    windows_text = texts.get("native/windows/README.md", "")
    if not canonical_order_present(windows_text, state["canonicalProofOrder"]):
        drifts.append(Drift("context_missing_canonical_proof_order", "native/windows/README.md", 1, "canonical proof order missing from Windows README"))

    for term in ["shellProtocolVersion", "hotOpsProtocolVersion", *state["requiredWindowsHotShellCapabilities"]]:
        if term not in windows_text:
            drifts.append(Drift("context_missing_protocol", "native/windows/README.md", 1, f"missing Windows protocol/capability term: {term}"))

    all_text = "\n".join(texts.values())
    if not all(needle in all_text for needle in GUARD_NEEDLES):
        drifts.append(Drift("context_missing_guard", "README.md", 1, "missing installed Windows shell proof guard with prove-hot-shell.py and installed app"))

    for item, text in texts.items():
        next_lines = next_section_lines(text)
        lines = text.splitlines()
        for number, line in enumerate(lines, start=1):
            for pattern in state["stalePatterns"]:
                if pattern not in line:
                    continue
                if number in next_lines:
                    if not next_line_has_marker(line):
                        drifts.append(Drift("context_stale_next_action", item, number, f"stale pattern in current next-action section: {pattern}"))
                elif not line_has_marker(line):
                    drifts.append(Drift("context_stale_pattern", item, number, f"stale pattern is not marked historical/stale/superseded: {pattern}"))

    map_text = texts.get("docs/context/MAP.md", "")
    map_next = "\n".join(line for idx, line in enumerate(map_text.splitlines(), start=1) if idx in next_section_lines(map_text) or "| `plugins/wasm-agent`" in line or "| `native/windows`" in line or "| `native/android`" in line)
    for command in state["canonicalProofOrder"]:
        if command not in map_text:
            drifts.append(Drift("context_missing_canonical_proof_order", "docs/context/MAP.md", 1, f"MAP.md does not mention current proof command: {command}"))
    for pattern in state["stalePatterns"]:
        if pattern in map_next and not any(marker in map_next.lower() for marker in HISTORICAL_MARKERS):
            drifts.append(Drift("context_stale_next_action", "docs/context/MAP.md", line_of(map_text, pattern), f"MAP.md next actions include stale pattern: {pattern}"))

    return drifts


def apply_fix(state: dict[str, Any]) -> list[str]:
    block = generated_block(state)
    changed: list[str] = []
    for item in GENERATED_DOCS:
        path = ROOT / item
        text = read_doc(path)
        new_text, replaced = replace_generated_block(text, block)
        if not replaced:
            if text.endswith("\n"):
                new_text = text + "\n## Current Active Goal\n\n" + block + "\n"
            else:
                new_text = text + "\n\n## Current Active Goal\n\n" + block + "\n"
        if new_text != text:
            path.write_text(new_text, encoding="utf-8")
            changed.append(item)
    state["updatedAt"] = datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")
    STATE_PATH.write_text(json.dumps(state, indent=2) + "\n", encoding="utf-8")
    changed.append(rel(STATE_PATH))
    return changed


def write_report(state: dict[str, Any], drifts: list[Drift], changed: list[str] | None = None) -> dict[str, Any]:
    REPORT_PATH.parent.mkdir(parents=True, exist_ok=True)
    classification = "context_sync_pass" if not drifts else drifts[0].classification
    report = {
        "ok": not drifts,
        "classification": classification,
        "checkedAt": datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z"),
        "activeStatePath": rel(STATE_PATH),
        "changed": changed or [],
        "drifts": [drift.as_dict() for drift in drifts],
    }
    REPORT_PATH.write_text(json.dumps(report, indent=2) + "\n", encoding="utf-8")
    return report


def print_report(report: dict[str, Any]) -> None:
    print(f"Context sync: {'PASS' if report['ok'] else 'FAIL'} ({report['classification']})")
    print(f"Report JSON: {rel(REPORT_PATH)}")
    for drift in report["drifts"]:
        print(f"{drift['classification']}: {drift['path']}:{drift['line']}: {drift['message']}")


def self_test() -> int:
    state = load_state()
    with tempfile.TemporaryDirectory() as tmp:
        root = Path(tmp)
        (root / "docs/context").mkdir(parents=True)
        (root / "native/windows").mkdir(parents=True)
        (root / "native/android").mkdir(parents=True)
        (root / "plugins/wasm-agent").mkdir(parents=True)
        passing = (ROOT / "fixtures/context-sync/passing.md").read_text(encoding="utf-8")
        for item in state["ownedDocs"]:
            path = root / item
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(passing, encoding="utf-8")
        clean = check_docs(state, root, include_generated_block=False)
        cases = [
            ("stale-next-build.md", "context_stale_next_action"),
            ("stale-next-ship-script.md", "context_stale_next_action"),
            ("missing-run-hot-operation.md", "context_missing_protocol"),
        ]
        failures: list[str] = []
        if clean:
            failures.append(f"passing fixture drifted: {[item.as_dict() for item in clean]}")
        for fixture, expected in cases:
            (root / "native/windows/README.md").write_text((ROOT / f"fixtures/context-sync/{fixture}").read_text(encoding="utf-8"), encoding="utf-8")
            drifts = check_docs(state, root, include_generated_block=False)
            if expected not in {drift.classification for drift in drifts}:
                failures.append(f"{fixture} did not produce {expected}: {[item.as_dict() for item in drifts]}")
            (root / "native/windows/README.md").write_text(passing, encoding="utf-8")
        (root / "plugins/wasm-agent/README.md").write_text((ROOT / "fixtures/context-sync/historical-stale-allowed.md").read_text(encoding="utf-8"), encoding="utf-8")
        drifts = check_docs(state, root, include_generated_block=False)
        if any("ship-hermes-wake.sh" in drift.message for drift in drifts):
            failures.append("historical stale pattern was not allowed")
        if failures:
            print("Context sync self-test: FAIL")
            for failure in failures:
                print(f"- {failure}")
            return 1
    print("Context sync self-test: PASS")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--fix", action="store_true", help="Update generated ACTIVE_STATE blocks only.")
    parser.add_argument("--self-test", action="store_true", help="Run focused checker fixture tests.")
    args = parser.parse_args()
    if args.self_test:
        return self_test()
    state = load_state()
    changed: list[str] = []
    if args.fix:
        changed = apply_fix(state)
        state = load_state()
    drifts = check_docs(state)
    report = write_report(state, drifts, changed)
    print_report(report)
    return 0 if report["ok"] else 1


if __name__ == "__main__":
    raise SystemExit(main())
